
development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  database: shiguma
  username: louis
  password: 1234
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  username: ton_nom_utilisateur
  collation: utf8mb4_general_ci
  password: ton_mot_de_passe
  database: nom_de_ta_base_de_donnees
  host: localhost
  port: 3306
  pool: 5